sudo: required

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

language: python
python:
  - "3.5"
install:
  - pip3 install pep8 
  - pip3 install --upgrade pyflakes
script:
  - "pep8 src"
  - "python3 -m pyflakes src"
  - make
