sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

language: python
python:
  - "3"
install:
  - pip3 install pep8 
  - pip3 install --upgrade pyflakes
  - sudo unlink /usr/bin/g++
  - sudo ln /usr/bin/g++-5 /usr/bin/g++
cashe: pip3
script:
  - "pep8 src"
  - "python3 -m pyflakes src"
  - make
